### PR TITLE
Update to intake2

### PR DESCRIPTION
**Pull request by martindurant**
breaking changes in some behaviour (but most were broken anyway)

reimplements patterns and auth

requires https://github.com/intake/intake/pull/837

most tests fixed, not all; some removed

### CODE REVIEW

**Comment by juntyr** [comment]
Thank you for working on this!

**Comment by juntyr** [comment]
Wow, thank you for getting this PR merged so quickly! Is there a (rough) time plan for when a new version will be released? I'd just like to know, there is no time pressure on my end :)

**Comment by martindurant** [comment]
There's no reason not to release now, except that anyone still installing intake-xarray will now get intake2 and something *might* break.

**Comment by juntyr** [comment]
> There's no reason not to release now, except that anyone still installing intake-xarray will now get intake2 and something _might_ break.

Could you release a new major version so that downstream packages depending on intake-xarray would have to explicitly upgrade to the new version (anyone that doesn't bound the dependency version in some way [ideally semantic versioning] explicitly opts into breaking changes imo)? I'm on the other side of the issue where I need to use intake v2 and am looking forward to the release

**Comment by martindurant** [comment]
We could call it 1.0.0, then. Or actually 2.0.0, to match intake - but it might be the last one, since you don't really need intake-xarray any more, except for backward compatibility!

**Comment by martindurant** [comment]
2.0.0 released. They might not be any more, depending on whether people decide to migrate to straight intake2 usage.

**Comment by juntyr** [comment]
> 2.0.0 released. They might not be any more, depending on whether people decide to migrate to straight intake2 usage.

Thanks for the release and the ping!

**Pull request merged**
