### PR TITLE
Allow netcdf4 engine in opendap driver

### PR DESCRIPTION
**Pull request by larsbuntemeyer**
draft pull request for https://github.com/intake/intake-xarray/issues/90

### CODE REVIEW

**Comment by martindurant** [comment]
I am fine with this kind of thing. Do you think it can be tested?

**Comment by larsbuntemeyer** [comment]
thx for the hint, should there be an exception test if opendap is used with netcdf4 engine and auth sessions?

**Comment by martindurant** [comment]
We should definitely raise a meaningful exception for the combinations that don't work, rather than letting it fail later.

**Comment by martindurant** [comment]
Everything looks good here.

Running again with the new CI setup.

**Comment by martindurant** [comment]
> should there be an exception test if opendap is used with netcdf4 engine and auth sessions

I leave this up to you. What happens right now in this case?

**Comment by larsbuntemeyer** [comment]
Ok, now the instantiation is allowed, but it raises a `ValueError`, e.g.
```
ValueError: Opendap session requires 'pydap' engine.
```
at discovery time. This is similar behaviour to the case if an invalid session identifier is selected. There is also a test now that will check this behaviour.

**Comment by larsbuntemeyer** [comment]
thx!

**Pull request merged**
