### PR TITLE
Remove CI warnings

### PR DESCRIPTION
**Pull request by ianthomas23**
Remove warnings in CI:

- Replace deprecated `mamba-org/provision-with-micromamba` with `mamba-org/setup-micromamba`.
- Update versions of actions that are using deprecated `node12`.

### CODE REVIEW

**Comment by martindurant** [comment]
We seem to be using dtype=np.float or (assert array.dtype == np.float), should be easy to fix.

**Comment by ianthomas23** [comment]
> We seem to be using dtype=np.float or (assert array.dtype == np.float), should be easy to fix.

OK, trying that out. Can you approve the CI workflow again please?

**Comment by martindurant** [comment]
oh, it seems to be rasterio that is doing this too

**Comment by ianthomas23** [comment]
@martindurant CI workflow needs approval again.

**Comment by martindurant** [comment]
There is still one failure there, but I can't immediately tell what the issue is.

**Comment by ianthomas23** [comment]
It looks like `test_http_server_files` is picking up the changes to `glob` in the latest `fsspec` release. I think I've fixed this now.

Needs another workflow approval :grin:

**Comment by ianthomas23** [comment]
With Python 3.8 we are using older `numpy` (3.8 support dropped recently) but new `rasterio`. So we are essentially debugging `rasterio`-`numpy` combinations.

**Comment by martindurant** [comment]
Hm, the failure in py38 would be because the newest numpy no longer builds on that version? We could change the supported versions to 3.9-3.11, seems reasonable.

**Comment by martindurant** [comment]
Sorry, your comment only just showed up. Let's test 3.9-3.11, but we don't need to change the python_requires as yet (but we could).

**Comment by ianthomas23** [comment]
I have pinned `rasterio` in the python 3.8 environment file and the tests pass locally so let's try that. Can you approve the workflow yet again?

**Comment by martindurant** [comment]
@ianthomas23 , is it too late to make you a member of Intake :)

**Comment by ianthomas23** [comment]
It is too late now, the tests have all passed!

**Pull request merged**
