### PR TITLE
Allow opening of fsspec cache files

### PR DESCRIPTION
**Pull request by martindurant**
@jsignell , you might be interested. The intent is to allow caching files and opening locally with resterio/netcdf, using fsspec mechanisms only (i.e., replacing the poorly-understood Intake mechanism, which remains available for now).

### CODE REVIEW

**Comment by martindurant** [comment]
(fails because it uses the released version of Intake)

**Comment by jsignell** [comment]
> (fails because it uses the released version of Intake)

Do you think we should be instead using the dev version of intake or we could add a test run where we use it.

**Comment by martindurant** [comment]
Not certain; also requires master fsspec...

**Comment by jsignell** [comment]
Probably best to just leave this in limbo until they are released then.

**Comment by martindurant** [comment]
closes https://github.com/intake/intake/issues/481

**Pull request merged**
