### PR TITLE
Supporting 'gs' protocol

### PR DESCRIPTION
**Pull request by rafa-guedes**
The zarr plugin only supports `gcs` protocol for google storage, could it support `gs` as well?

### CODE REVIEW

**Comment by martindurant** [comment]
Whilst this is a fine change, fsspec not provides [get_mapper](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.get_mapper), which will allow for any of the protocols it knows about, which includes gcs and gs as well as [many more](https://github.com/intake/filesystem_spec/blob/master/fsspec/registry.py#L10) that zarr didn't previously have the ability to use. I recommend removing this function in favour of the fsspec one (tests will obviously need to install fsspec).

**Comment by rafa-guedes** [comment]
Sorry for the many little commits here, I'm a bit new to travis-ci and was struggling a bit to find out where fsspec needed to be installed to make those tests pass!

**Comment by martindurant** [comment]
This all looks good to me.

I think that the same code should exist in xarray and zarr themselves, though. Are you interested in finding the relevant places?

At `from fsspec import filesystem, get_mapper` I would add a version check and helpful import error message.

**Comment by rafa-guedes** [comment]
> I think that the same code should exist in xarray and zarr themselves, though.

Not sure what exactly you mean here..

> At from fsspec import filesystem, get_mapper I would add a version check and helpful import error message.

What should the minimum fsspec version be please? I had a quick look and it looks like all those imports have existed at the expected modules since the first release [0.0.1](https://github.com/intake/filesystem_spec/tree/0.0.1)..

**Comment by martindurant** [comment]
I mean that `xarray.open*("webhdfs://path")`, for example, should become an option, now that we have a centralised place for turning URLs into mapping storage.

> What should the minimum fsspec version be 

I would set it to one of the releases in the last couple of weeks, as a lot has changed internally; perhaps the very latest release right now (0.3.6), since fsspec itself doesn't have any deps.

**Comment by rafa-guedes** [comment]
@martindurant I have fixed minimum version for `fsspec>=0.3.6` within the zarr plugin code, and also in installation requirements.

> I mean that xarray.open*("webhdfs://path"), for example, should become an option

I'm happy to try and have a go at this, it would be really useful indeed.

**Comment by martindurant** [comment]
Let's merge and release this after Dask and Intake are released - in a couple of days, maybe.

**Comment by martindurant** [comment]
Can you test with #46 ? I think that will have provided this functionality.

**Comment by rafa-guedes** [comment]
It breaks with HTTP error when trying to load as dask, see below. I don't know, it may be some authorisation issue on my end, but this does work with the code version in this pull request.

```
In [4]: dset = cat.hindcast.era5_wind10m.to_dask()                                                                                                                                                                   
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/.virtualenvs/py3/local/lib/python3.7/site-packages/fsspec/mapping.py in __getitem__(self, key, default)
     73         try:
---> 74             result = self.fs.cat(key)
     75         except:

</home/rguedes/.virtualenvs/py3/local/lib/python3.7/site-packages/decorator.py:decorator-gen-129> in cat(self, path)

~/.virtualenvs/py3/local/lib/python3.7/site-packages/gcsfs/core.py in _tracemethod(f, self, *args, **kwargs)
     53 
---> 54     return f(self, *args, **kwargs)
     55 

~/.virtualenvs/py3/local/lib/python3.7/site-packages/gcsfs/core.py in cat(self, path)
    741         r = self.session.get(u2)
--> 742         r.raise_for_status()
    743         if 'X-Goog-Hash' in r.headers:

~/.virtualenvs/py3/local/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 

HTTPError: 401 Client Error: Unauthorized for url: https://www.googleapis.com/download/storage/v1/b/oceanum-era5/o/wind_10m.zarr%2F.zmetadata?alt=media

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-4-ef68011be1ae> in <module>
----> 1 dset = cat.hindcast.era5_wind10m.to_dask()

~/.virtualenvs/py3/local/lib/python3.7/site-packages/intake_xarray/base.py in to_dask(self)
     67     def to_dask(self):
     68         """Return xarray object where variables are dask arrays"""
---> 69         return self.read_chunked()
     70 
     71     def close(self):

~/.virtualenvs/py3/local/lib/python3.7/site-packages/intake_xarray/base.py in read_chunked(self)
     42     def read_chunked(self):
     43         """Return xarray object (which will have chunks)"""
---> 44         self._load_metadata()
     45         return self._ds
     46 

~/.virtualenvs/py3/local/lib/python3.7/site-packages/intake/source/base.py in _load_metadata(self)
    115         """load metadata only if needed"""
    116         if self._schema is None:
--> 117             self._schema = self._get_schema()
    118             self.datashape = self._schema.datashape
    119             self.dtype = self._schema.dtype

~/.virtualenvs/py3/local/lib/python3.7/site-packages/intake_xarray/base.py in _get_schema(self)
     16 
     17         if self._ds is None:
---> 18             self._open_dataset()
     19 
     20             metadata = {

~/.virtualenvs/py3/local/lib/python3.7/site-packages/intake_xarray/xzarr.py in _open_dataset(self)
     29 
     30         self._mapper = get_mapper(self.urlpath, **self.storage_options)
---> 31         self._ds = xr.open_zarr(self._mapper, **self.kwargs)
     32 
     33     def close(self):

~/.virtualenvs/py3/local/lib/python3.7/site-packages/xarray/backends/zarr.py in open_zarr(store, group, synchronizer, chunks, decode_cf, mask_and_scale, decode_times, concat_characters, decode_coords, drop_variables, consolidated, overwrite_encoded_chunks, **kwargs)
    554     zarr_store = ZarrStore.open_group(store, mode=mode,
    555                                       synchronizer=synchronizer,
--> 556                                       group=group, consolidated=consolidated)
    557     ds = maybe_decode_store(zarr_store)
    558 

~/.virtualenvs/py3/local/lib/python3.7/site-packages/xarray/backends/zarr.py in open_group(cls, store, mode, synchronizer, group, consolidated, consolidate_on_close)
    248         if consolidated:
    249             # TODO: an option to pass the metadata_key keyword
--> 250             zarr_group = zarr.open_consolidated(store, **open_kwargs)
    251         else:
    252             zarr_group = zarr.open_group(store, **open_kwargs)

~/.virtualenvs/py3/local/lib/python3.7/site-packages/zarr/convenience.py in open_consolidated(store, metadata_key, mode, **kwargs)
   1180 
   1181     # setup metadata sotre
-> 1182     meta_store = ConsolidatedMetadataStore(store, metadata_key=metadata_key)
   1183 
   1184     # pass through

~/.virtualenvs/py3/local/lib/python3.7/site-packages/zarr/storage.py in __init__(self, store, metadata_key)
   2455             d = store[metadata_key].decode()  # pragma: no cover
   2456         else:  # pragma: no cover
-> 2457             d = store[metadata_key]
   2458         meta = json_loads(d)
   2459 

~/.virtualenvs/py3/local/lib/python3.7/site-packages/fsspec/mapping.py in __getitem__(self, key, default)
     76             if default is not None:
     77                 return default
---> 78             raise KeyError(key)
     79         return result
     80 

KeyError: 'oceanum-era5/wind_10m.zarr/.zmetadata'
```

**Comment by martindurant** [comment]
Yep, looks like auth. Follow the guidelines in gcsfs for how to establish credentials

**Comment by rafa-guedes** [comment]
I have been authenticating it via json key, it has been working so far. It works using `fsspec` directly as shown below. It also works with `intake_xarray`, when using this fork #42. It keeps breaking with the latest release of `intake_xarray` though. I was using `anon` for token in my intake config, I now changed it to `None` and the error is different, see below (still works with #42 though).

```
In [6]: from fsspec import get_mapper

In [7]: import xarray as xr

In [8]: fsmap = get_mapper("gs://oceanum-era5/wind_10m.zarr")

In [9]: dset = xr.open_zarr(fsmap, consolidated=True)

In [10]: dset
Out[10]:
<xarray.Dataset>
Dimensions:    (latitude: 721, longitude: 1440, time: 354264)
Coordinates:
  * latitude   (latitude) float32 90.0 89.75 89.5 89.25 ... -89.5 -89.75 -90.0
  * longitude  (longitude) float32 0.0 0.25 0.5 0.75 ... 359.25 359.5 359.75
  * time       (time) datetime64[ns] 1979-01-01 ... 2019-05-31T23:00:00
Data variables:
    u10        (time, latitude, longitude) float32 dask.array<shape=(354264, 721, 1440), chunksize=(744, 100, 100)>
    v10        (time, latitude, longitude) float32 dask.array<shape=(354264, 721, 1440), chunksize=(744, 100, 100)>
Attributes:
    Conventions:  CF-1.6
    history:      2019-08-01 10:44:37 GMT by grib_to_netcdf-2.10.0: /opt/ecmw...
```

```
In [3]: dset = cat.hindcast.era5_wind10m.to_dask()
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-ef68011be1ae> in <module>
----> 1 dset = cat.hindcast.era5_wind10m.to_dask()

~/Envs/py3/lib/python3.7/site-packages/intake_xarray/base.py in to_dask(self)
     67     def to_dask(self):
     68         """Return xarray object where variables are dask arrays"""
---> 69         return self.read_chunked()
     70
     71     def close(self):

~/Envs/py3/lib/python3.7/site-packages/intake_xarray/base.py in read_chunked(self)
     42     def read_chunked(self):
     43         """Return xarray object (which will have chunks)"""
---> 44         self._load_metadata()
     45         return self._ds
     46

~/Envs/py3/lib/python3.7/site-packages/intake/source/base.py in _load_metadata(self)
    115         """load metadata only if needed"""
    116         if self._schema is None:
--> 117             self._schema = self._get_schema()
    118             self.datashape = self._schema.datashape
    119             self.dtype = self._schema.dtype

~/Envs/py3/lib/python3.7/site-packages/intake_xarray/base.py in _get_schema(self)
     16
     17         if self._ds is None:
---> 18             self._open_dataset()
     19
     20             metadata = {

~/Envs/py3/lib/python3.7/site-packages/intake_xarray/xzarr.py in _open_dataset(self)
     28         from fsspec import get_mapper
     29
---> 30         self._mapper = get_mapper(self.urlpath, **self.storage_options)
     31         self._ds = xr.open_zarr(self._mapper, **self.kwargs)
     32

~/Envs/py3/lib/python3.7/site-packages/fsspec/mapping.py in get_mapper(url, check, create, **kwargs)
    155     protocol, path = split_protocol(url)
    156     cls = get_filesystem_class(protocol)
--> 157     fs = cls(**kwargs)
    158     # Removing protocol here - could defer to each open() on the backend
    159     return FSMap(path, fs, check, create)

~/Envs/py3/lib/python3.7/site-packages/gcsfs/core.py in __init__(self, project, access, token, block_size, consistency, cache_timeout, secure_serialize, check_connection, requests_timeout, **kwargs)
    293         self._listing_cache = {}
    294         self.session = None
--> 295         self.connect(method=token)
    296
    297         if not secure_serialize:

~/Envs/py3/lib/python3.7/site-packages/gcsfs/core.py in connect(self, method)
    404         if method not in ['google_default', 'cache', 'cloud', 'token', 'anon',
    405                           'browser', None]:
--> 406             self._connect_token(method)
    407         elif method is None:
    408             for meth in ['google_default', 'cache', 'anon']:

~/Envs/py3/lib/python3.7/site-packages/gcsfs/core.py in _connect_token(self, token)
    358         if isinstance(token, str):
    359             if not os.path.exists(token):
--> 360                 raise FileNotFoundError(token)
    361             try:
    362                 # is this a "service" token?

FileNotFoundError: None
```

**Comment by rafa-guedes** [comment]
The issue was with my token. I set it as `None` in my intake config, but it was parsed as a string. In #42, `self.storage_options` was not being passed to `get_mapper` and therefore token was being ignored, that is why it was not breaking.

Thanks, will close this pull request!

**Pull request closed without merging**
