### PR TITLE
Bump setup-miniconda from v1 to v2 and remove Travis CI

### PR DESCRIPTION
**Pull request by weiji14**
Fixes Github Actions CI error:

```
Error: Unable to process command '::add-path::/usr/share/miniconda/condabin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

### CODE REVIEW

**Comment by martindurant** [comment]
Should we disable travisCI now?

**Comment by weiji14** [comment]
Sure, keep things simple.

**Comment by martindurant** [comment]
Would b happy to see it done here. I actually don't know how! I turned off builds in the travis UI (well, the one on .com, where this repo shows up, but not apparently where the build happens...)

**Comment by weiji14** [comment]
> Would b happy to see it done here. I actually don't know how! I turned off builds in the travis UI (well, the one on .com, where this repo shows up, but not apparently where the build happens...)

I've deleted the `.travis.yml` file which should do the trick :laughing:

**Comment by martindurant** [comment]
Great

**Pull request merged**
