### PR TITLE
added mfdataset to opendap

### PR DESCRIPTION
**Pull request by kthyng**
Hi! I would like to use mfdataset with opendap and I put it in really simply. I wasn't sure how to incorporate `store` like in `open_dataset`, if that is possible. Also, I ran tests locally but on the master branch I had 5 errors, and the same 5 errors with this change so I figured it was something to do with my local configuration rather than the changes I made.

### CODE REVIEW

**Comment by aaronspring** [comment]
I am surprised that * works on urls. Could you add a test for urlpath as list and another containing *?

**Comment by kthyng** [comment]
@aaronspring Ah, you are right about that — "*" will not work with opendap (I copied it uncritically from the `open_netcdf` function). I removed that.

I added a test for `open_opendap` with a single url and a list of two urls.

What do you think?

**Comment by aaronspring** [comment]
Ok. So the passing of kwargs for either mfdataset or dataset is now implicitly set by the type of urlpath. list makes mfdataset and allows parallel=True.

works for me. 

Does that solution also work for your intake catalog with 127 datasets?

**Comment by martindurant** [comment]
I'm only watching this thread, please ping me if you need anything

**Comment by kthyng** [comment]
@aaronspring Yep! It works with a big list of remote files like as described in [the `intake-thredds` issue](https://github.com/intake/intake-thredds/issues/70) except doesn't rely on `intake-thredds`.

Any idea why some checks were not successful on this PR?

**Comment by aaronspring** [comment]
`upstream` issues are not your fault. same problem in https://github.com/intake/intake-xarray/pull/109 mentioned also in https://github.com/rasterio/rasterio/issues/2381

**Comment by kthyng** [comment]
Ok, just let me know if I should do anything to move this forward! Thanks @aaronspring and @martindurant.

**Comment by aaronspring** [comment]
I agree with this PR. But cannot merge. Can you @martindurant? Or should we wait until the rasterio issue is solved?

**Comment by martindurant** [comment]
I suppose rasterio is unrelated, so I can merge this now. Would you like to be a maintainer here, @aaronspring ?

**Comment by aaronspring** [comment]
I'd be happy to join @martindurant

**Comment by kthyng** [comment]
Thank you @aaronspring and @martindurant!

**Comment by aaronspring** [comment]
Thank you @kthyng for this addition

**Pull request merged**
